# Sidebar navigation

- label: " âš¡ï¸ Introduction"
  link: "/"
- label: Basic
  items:
    - label: "ğŸ’» Basic Cli"
      link: "/basic/cli"
    - label: "ğŸ“Œ Github - Assignment"
      link: "/basic/git"
- label: "Conditional & Data Type"
  items:
    - label: "ğŸª— Advanced Conditional"
      link: "/conditional/advanced-conditional"
- label: Loop & Iteration
  items:
    - label: "-"
      link: "/#"
- label: EcmaScript 6
  items:
    - label: "-"
      link: "/#"
- label: Function
  items:
    - label: "-"
      link: "/#"
- label: Array
  items:
    - label: "-"
      link: "/#"
- label: Modular Function
  items:
    - label: "-"
      link: "/#"
- label: Object
  items:
    - label: "-"
      link: "/#"
- label: Array Of Object
  items:
    - label: "-"
      link: "/#"
- label: ğŸŒ Community
  items:
    - label: "Github"
      link: https://github.com/bagusrizkis/lectureH8
